version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get install -y gettext-base
  pre_build:
    commands:
      - aws ecr get-login-password --region {{aws_region}} | docker login --username AWS --password-stdin {{container_registry}}
      - IMAGE_TAG=$(date '+%Y%m%d%H%M')
  build:
    commands:
      - >
        for dockerfile in $(find . -name Dockerfile -exec realpath {} \;); 
        do
          cd $(dirname $dockerfile);
          DOCKER_IMAGE=$(echo $dockerfile | awk -F '/' '{print $(NF-1)}');
          REPOSITORY_URI="{{container_registry}}/${DOCKER_IMAGE}"
          docker build -t ${REPOSITORY_URI}:latest .; 
          docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:$IMAGE_TAG;
          docker push ${REPOSITORY_URI}:latest
          docker push $}REPOSITORY_URI}:$IMAGE_TAG
        done
  post_build:
    commands:
      - docker images
      - ls -l
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      # - envsubst < microservice.yml > microservice_deployment.yml
artifacts:
  files:
    - microservices.yaml
    # - deploy_app.sh
    # - appspec.yml
