version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - cd microservice-kubernetes
      - mvn package
artifacts:
  files:
    - microservice-kubernetes/microservice-kubernetes-demo/...UPDATE ME .../target/spring-0.0.1-SNAPSHOT.jar
    - docker/Dockerfile
    - scripts/deploy_app.sh
    - k8s/microservices.yml
    - appspec.yml
  discard-paths: yes
