version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - cd microservice-kubernetes/microservice-kubernetes-demo
      - mvn clean package
artifacts:
  files:
    - '*/*/target/*-0.0.1-SNAPSHOT.jar'
    - '*/*/Dockerfile'
    # - appspec.yml
  base-directory: microservice-kubernetes
  discard-paths: no
