version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get install -y gettext-base
  pre_build:
    commands:
      - IMAGE_TAG=$(date '+%Y%m%d%H%M')
      - CONTAINER_REGISTRY="{{container_registry}}"
      - aws ecr get-login-password --region {{aws_region}} | docker login --username AWS --password-stdin
  build:
    commands:
      - >
        for dockerfile in $(find . -name Dockerfile -exec realpath {} \;); 
        do
          cd $(dirname $dockerfile);
          DOCKER_IMAGE=$(echo $dockerfile | awk -F '/' '{print $(NF-1)}');
          REPOSITORY_URI="${CONTAINER_REGISTRY}/${DOCKER_IMAGE}";
          docker build -t ${REPOSITORY_URI}:latest .; 
          docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:$IMAGE_TAG;
          aws ecr describe-repositories --repository-names ${DOCKER_IMAGE} || aws ecr create-repository --repository-name ${DOCKER_IMAGE};
          docker push ${REPOSITORY_URI}:latest;
          docker push ${REPOSITORY_URI}:$IMAGE_TAG;
        done
  post_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - envsubst < microservice-kubernetes-demo/microservices.yaml > microservice_deployment.yml
artifacts:
  files:
    - microservices.yaml
    # - deploy_app.sh
    # - appspec.yml
