---
aws_region: 'us-east-1'
codebuild_project_name: 'Microservice'
codebuild_project_description: 'Microservice project'
codebuild_buildspec: buildspec.yml
codebuild_role_policies: []
codebuild_privileged_mode: false
