---
aws_region: 'us-east-1'
codebuild_project_name: 'test'
codebuild_project_description: 'test project'
codebuild_buildspec: buildspec.yml
codebuild_role_policies: []
codebuild_privileged_mode: false
