---
- name: Create Codecommit repo
  aws_codecommit:
    name: '{{codecommit_repo_name}}'
    state: present
    region: '{{aws_region}}'
    validate_certs: no
    aws_access_key: '{{aws_access_key}}'
    aws_secret_key: '{{aws_secret_key}}'
  register: codecommit_repo

- name: Git repo URL
  set_fact:
    codecommit_repo_url: '{{codecommit_repo.repository_metadata.clone_url_http}}'
  when: codecommit_repo.repository_metadata is defined

- name: Git repo URL
  set_fact:
    codecommit_repo_url: 'https://git-codecommit.{{aws_region}}.amazonaws.com/v1/repos/{{codecommit_repo_name}}'
  when: codecommit_repo.repository_metadata is undefined

- name: Git redirect remote to Codecommit
  shell: git remote remove origin; git remote add origin '{{codecommit_repo_url}}'
  args:
    chdir: '{{git_repo_path}}'
  environment:
    AWS_DEFAULT_REGION: '{{aws_region}}'
    AWS_ACCESS_KEY_ID: '{{aws_access_key}}'
    AWS_SECRET_ACCESS_KEY: '{{aws_secret_key}}'

- name: Configure credential helper
  shell: git config --local credential.helper '!aws codecommit credential-helper $@'; git config --local credential.UseHttpPath true
  args:
    chdir: '{{git_repo_path}}'
  environment:
    AWS_DEFAULT_REGION: '{{aws_region}}'
    AWS_ACCESS_KEY_ID: '{{aws_access_key}}'
    AWS_SECRET_ACCESS_KEY: '{{aws_secret_key}}'

- name: Git push to Codecommit
  shell: git push --set-upstream origin master
  args:
    chdir: '{{git_repo_path}}'
  environment:
    AWS_DEFAULT_REGION: '{{aws_region}}'
    AWS_ACCESS_KEY_ID: '{{aws_access_key}}'
    AWS_SECRET_ACCESS_KEY: '{{aws_secret_key}}'

