---
aws_ami_name: 'ubuntu/images/hvm-ssd/ubuntu-bionic-18.04'
aws_ami_owner: '099720109477'

kubectl_source: 'https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.9/2019-06-21/bin/linux/amd64/kubectl'
iam_authenticator_source: 'https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator'
codedeploy_source: 'https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install'
deployment_server_role_name: deployment-server-role
deployment_server_policy_name: deployment-server-policy

disk_type: 'gp2'
deployment_server_instance:
    instance_type: t2.micro
    subnet_id: '{{deployment_subnet_id}}'
    security_group: '{{deployment_security_group}}'
    name: 'Deployment server'
    user_data: |
      #!/bin/bash
      apt-get update
      apt-get install -y software-properties-common python-pip apt-utils
      apt-add-repository --yes --update ppa:ansible/ansible
      apt-get install -y ansible ruby
      pip install boto boto3
      pip install awscli --upgrade
      cd /usr/bin
      echo kubectl
      curl -o kubectl '{{kubectl_source}}'
      chmod 755 kubectl
      echo aws-iam-authenticator
      curl -o aws-iam-authenticator '{{iam_authenticator_source}}'
      chmod 755 aws-iam-authenticator
      cd /home/ubuntu
      echo codedeploy
      curl -o install '{{codedeploy_source}}'
      chmod 755 install
      ./install auto
